addressing review for arxiv-base image (ARXIVNG-183)

diff --git a/arxiv-base/Dockerfile b/arxiv-base/Dockerfile
--- a/arxiv-base/Dockerfile
+++ b/arxiv-base/Dockerfile
@@ -2,8 +2,15 @@
 
 FROM centos:centos7
 
+#
+# Below we use && chaining and an embedded script in a single RUN
+# command to keep image size and layer count to a minimum, while
+# the embedded script will make 'docker build' fail fast
+# if a package is missing.
+#
 RUN yum -y update && yum -y install epel-release \
-&& yum -y install https://centos7.iuscommunity.org/ius-release.rpm \  
+&& yum -y install https://centos7.iuscommunity.org/ius-release.rpm \
+&& yum -y update --security \
 && echo $'#!/bin/bash\n\
 PKGS_TO_INSTALL=$(cat <<-END\n\
   ca-certificates\n\
@@ -17,7 +24,10 @@ END\n\
 )\n\
 for pkg in ${PKGS_TO_INSTALL}; do\n\
   # Stop executing if at least one package is not available:\n\
-  yum info ${pkg} || ( echo "yum could not find package ${pkg}"; exit 1 )\n\
+  yum info ${pkg} || {\n\
+    echo "yum could not find package ${pkg}"\n\
+    exit 1\n\
+  }\n\
 done\n\
 yum -y install ${PKGS_TO_INSTALL}\n' >> /tmp/safe_yum.sh \
 && /bin/bash /tmp/safe_yum.sh \
